import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Feat from '../../components/Feat';
import Header from '../../components/Header';
import Layout from '../../components/Layout';

const Home: NextPage = () => {
  return (
    <div className='works-page'>
      <Head>
        <title>Photomarin | Works</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header
        text={{
          subtitle: 'This is my works',
          description: 'Get in touch and contact me',
        }}
        background='/assets/images/Themes/Family/family-wrapper.jpg'
      />
      <div className='main'>
        <div className='main-content'>
          <div className='main-wrapper'>
            <h2>Works</h2>
            <div className='feat'>
              <Feat
                img='/assets/images/Themes/Family/family-cover.jpg'
                title='Family'
                url='/themes/family'
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
