/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable jsx-a11y/alt-text */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Feat from '../../components/Feat';
import Header from '../../components/Header';
import Layout from '../../components/Layout';

const Rita: NextPage = () => {
  return (
    <div className='works-page'>
      <Head>
        <title>Photomarin | Works | Rita</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header
        text={{
          subtitle: `This is Rita's Family`,
          description: 'Get in touch and contact me',
        }}
        background='/assets/images/rita-family-wrapper.jpg'
      />
      <div className='main'>
        <div className='main-content'>
          <div className='main-wrapper'>
            <h2>Rita's Family</h2>
            <div className='main-wrapper-pictures'>
              <img src='/assets/images/rita-family-1.jpg' alt='' />
              <img src='/assets/images/rita-family-2.jpg' alt='' />
              <img src='/assets/images/rita-family-3.jpg' alt='' />
              <img src='/assets/images/rita-family-4.jpg' alt='' />
              <img src='/assets/images/rita-family-5.jpg' alt='' />
              <img src='/assets/images/rita-family-6.jpg' alt='' />
              <img src='/assets/images/rita-family-7.jpg' alt='' />
              <img src='/assets/images/rita-family-8.jpg' alt='' />
              <img src='/assets/images/rita-family-9.jpg' alt='' />
              <img src='/assets/images/rita-family-10.jpg' alt='' />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Rita;
