import type { NextPage } from 'next';
import Head from 'next/head';
import Feat from '../../../components/Feat';
import Header from '../../../components/Header';

const Business: NextPage = () => {
  return (
    <div className='business-page'>
      <Head>
        <title>Photomarin | Themes | Business</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header
        text={{
          subtitle: 'This is my theme about business',
          description: 'Get in touch and contact me',
        }}
        background='/assets/images/Business/wrapper.jpg'
      />
      <div className='main'>
        <div className='main-content'>
          <div className='main-wrapper'>
            <h2>My works about Business</h2>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro
              esse deserunt enim, rem id ut expedita saepe minima perspiciatis
              nihil!
            </p>
            <div className='feat'>
              <Feat
                img='/assets/images/Business/Valeriy/cover.jpg'
                title={`Valeriy`}
                url='/themes/business/valeriy'
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Business;
