import type { NextPage } from 'next';
import Head from 'next/head';
import Feat from '../../../components/Feat';
import Header from '../../../components/Header';

const LoveStory: NextPage = () => {
  return (
    <div className='family-page'>
      <Head>
        <title>Photomarin | Themes | Love Story</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header
        text={{
          subtitle: 'This is my theme about family',
          description: 'Get in touch and contact me',
        }}
        background='/assets/images/Love-story/wrapper.jpg'
      />
      <div className='main'>
        <div className='main-content'>
          <div className='main-wrapper'>
            <h2>My works about Love Story</h2>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro
              esse deserunt enim, rem id ut expedita saepe minima perspiciatis
              nihil!
            </p>
            <div className='feat'>
              <Feat
                img='/assets/images/Love-story/Anton/cover.jpg'
                title={`Anton`}
                url='/themes/love-story/anton'
              />
              <Feat
                img='/assets/images/Love-story/Oleg/cover.jpg'
                title={`Oleg`}
                url='/themes/love-story/oleg'
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LoveStory;
