import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Feat from '../../../components/Feat';
import Header from '../../../components/Header';
import Layout from '../../../components/Layout';

const Art: NextPage = () => {
  return (
    <div className='art-page'>
      <Head>
        <title>Photomarin | Themes | Art</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header
        text={{
          subtitle: 'This is my theme about art',
          description: 'Get in touch and contact me',
        }}
        background='/assets/images/Art/wrapper.jpg'
      />
      <div className='main'>
        <div className='main-content'>
          <div className='main-wrapper'>
            <h2>My works about Art</h2>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro
              esse deserunt enim, rem id ut expedita saepe minima perspiciatis
              nihil!
            </p>
            <div className='feat'>
              <Feat
                img='/assets/images/Art/Angel/cover.jpg'
                title={`Angel`}
                url='/themes/art/angel'
              />
              <Feat
                img='/assets/images/Art/Jack/cover.jpg'
                title={`Jack`}
                url='/themes/art/jack'
              />
              <Feat
                img='/assets/images/Art/Potter/cover.jpg'
                title={`Potter`}
                url='/themes/art/potter'
              />
            </div>
            <div className='feat'>
              <Feat
                img='/assets/images/Art/Relaxation/cover.jpg'
                title={`Relaxation`}
                url='/themes/art/relaxation'
              />
              <Feat
                img='/assets/images/Art/XV/cover.jpg'
                title={`XV`}
                url='/themes/art/xv'
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Art;
