import type { NextPage } from 'next';
import Head from 'next/head';
import Feat from '../../../components/Feat';
import Header from '../../../components/Header';

const Family: NextPage = () => {
  return (
    <div className='family-page'>
      <Head>
        <title>Photomarin | Themes | Family</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header
        text={{
          subtitle: 'This is my theme about family',
          description: 'Get in touch and contact me',
        }}
        background='/assets/images/Family/wrapper.jpg'
      />
      <div className='main'>
        <div className='main-content'>
          <div className='main-wrapper'>
            <h2>My works about Family</h2>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro
              esse deserunt enim, rem id ut expedita saepe minima perspiciatis
              nihil!
            </p>
            <div className='feat'>
              <Feat
                img='/assets/images/Family/Ira/cover.jpg'
                title={`Ira`}
                url='/themes/family/ira'
              />
              <Feat
                img='/assets/images/Family/Olga/cover.jpg'
                title={`Olga`}
                url='/themes/family/olga'
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Family;
